In [8]:
import pandas as pd

In [9]:
path = r"H:\python\3° etapa\atv 3\Tabela_3_Areas_gerais_de_formacao_na_graduacao.xlsx"

In [10]:
formacao_bruto = pd.read_excel(path, header=None)

In [19]:
formacao_bruto

,0,1,2,3,4,5,6,7,8,9
0,Tabela 10063 - Pessoas com nível superior comp...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"Brasil, Grande Região e Unidade da Federação",Total,NaN,NaN,"Ciência, Tecnologia, Engenharias e Matemática",NaN,NaN,"Educação, Serviços pessoais, Saúde e Bem-estar",NaN,NaN
2,NaN,Total,Homens,Mulheres,Total,Homens,Mulheres,Total,Homens,Mulheres
3,Brasil,25854291,10478534,15375757,4149041,2750422,1398619,8079707,1677985,6401723
4,Norte,1525166,590558,934609,209657,133055,76601,599785,141169,458616
5,Nordeste,4748933,1744994,3003939,621388,389993,231395,1822087,363905,1458181
6,Sudeste,12828829,5391638,7437191,2328122,1588874,739247,3652397,768288,2884108
7,Sul,4338861,1768855,2570005,662916,427372,235543,1256291,248574,1007718
8,Centro-Oeste,2412502,982489,1430013,326959,211124,115834,749148,156048,593101
9,Rondônia,164632,62766,101866,20538,11863,8675,63584,13963,49622
10,Acre,84300,33291,51009,10364,6237,4128,33379,9121,24258
11,Amazonas,342566,141059,201507,52669,34749,17919,121988,30738,91249
12,Roraima,67045,25585,41460,8016,4958,3057,23977,5880,18098
13,Pará,601096,229285,371811,86691,55481,31211,248397,58128,190270
14,Amapá,89191,35085,54106,11349,7464,3885,36754,9794,26960
15,Tocantins,176336,63485,112851,20028,12304,7724,71705,13548,58158
16,Maranhão,468681,161352,307329,55068,33820,21248,206222,40667,165555
17,Piauí,304955,108371,196584,37135,21668,15467,128416,25959,102457
18,Ceará,759303,285013,474290,99062,63935,35126,294578,64582,229996
19,Rio Grande do Norte,339913,131178,208735,46857,30398,16459,135434,28273,107161
20,Paraíba,390742,147221,243521,52223,33369,18855,150862,30025,120837
21,Pernambuco,852481,321587,530893,120260,73253,47007,281695,57333,224362
22,Alagoas,267996,98462,169534,33596,21398,12198,106971,20060,86911
23,Sergipe,218255,80608,137646,29020,17596,11422,83176,16801,66376
24,Bahia,1146608,411202,735406,148167,94556,53612,434735,80208,354528
25,Minas Gerais,2615434,1031532,1583902,452258,291778,160479,832482,157960,674521
26,Espírito Santo,491101,193756,297344,75667,49648,26018,161332,29788,131544
27,Rio de Janeiro,2243707,942645,1301062,406529,265723,140805,612263,145864,466399
28,São Paulo,7478587,3223705,4254883,1393668,981724,411944,2046321,434677,1611645
29,Paraná,1687930,695425,992505,255635,166579,89056,501471,98191,403280
30,Santa Catarina,1162515,489557,672958,185742,126554,59188,333537,67571,265964
31,Rio Grande do Sul,1488416,583873,904542,221541,134240,87300,421284,82812,338472
32,Mato Grosso do Sul,366249,145341,220908,46340,28241,18100,128352,26911,101443
33,Mato Grosso,450264,173267,276997,56776,33307,23468,141121,27052,114069
34,Goiás,879270,350828,528443,116867,74711,42156,288616,56564,232052
35,Distrito Federal,716719,313054,403665,106976,74866,32109,191061,45521,145538
36,Fonte: IBGE - Censo Demográfico,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
formacao_total = formacao_bruto.iloc[3:36, 0:4]

In [73]:
formacao_stem = formacao_bruto.iloc[3:36, [0, 4, 5, 6] ]
formacao_stem = formacao_stem.rename(columns={0: "uf"})
formacao_stem = formacao_stem.rename(columns={4: "total"})
formacao_stem = formacao_stem.rename(columns={5: "total_homens"})
formacao_stem = formacao_stem.rename(columns={6: "total_mulheres"})

formacao_stem

                     uf    total total_homens total_mulheres
3                Brasil  4149041      2750422        1398619
4                 Norte   209657       133055          76601
5              Nordeste   621388       389993         231395
6               Sudeste  2328122      1588874         739247
7                   Sul   662916       427372         235543
8          Centro-Oeste   326959       211124         115834
9              Rondônia    20538        11863           8675
10                 Acre    10364         6237           4128
11             Amazonas    52669        34749          17919
12              Roraima     8016         4958           3057
13                 Pará    86691        55481          31211
14                Amapá    11349         7464           3885
15            Tocantins    20028        12304           7724
16             Maranhão    55068        33820          21248
17                Piauí    37135        21668          15467
18                Ceará    99062        63935          35126
19  Rio Grande do Norte    46857        30398          16459
20              Paraíba    52223        33369          18855
21           Pernambuco   120260        73253          47007
22              Alagoas    33596        21398          12198
23              Sergipe    29020        17596          11422
24                Bahia   148167        94556          53612
25         Minas Gerais   452258       291778         160479
26       Espírito Santo    75667        49648          26018
27       Rio de Janeiro   406529       265723         140805
28            São Paulo  1393668       981724         411944
29               Paraná   255635       166579          89056
30       Santa Catarina   185742       126554          59188
31    Rio Grande do Sul   221541       134240          87300
32   Mato Grosso do Sul    46340        28241          18100
33          Mato Grosso    56776        33307          23468
34                Goiás   116867        74711          42156
35     Distrito Federal   106976        74866          32109

In [72]:
formacao_matematica.to_csv(r"H:\python\3° etapa\atv 3\formacao_matematica.csv", sep = ";", encoding="latin1")

In [74]:
formacao_saude = formacao_bruto.iloc[3:36, [0, 7, 8, 9] ]
formacao_saude = formacao_saude.rename(columns={0: "uf"})
formacao_saude = formacao_saude.rename(columns={7: "total"})
formacao_saude = formacao_saude.rename(columns={8: "total_homens"})
formacao_saude = formacao_saude.rename(columns={9: "total_mulheres"})

formacao_saude

                     uf    total total_homens total_mulheres
3                Brasil  8079707      1677985        6401723
4                 Norte   599785       141169         458616
5              Nordeste  1822087       363905        1458181
6               Sudeste  3652397       768288        2884108
7                   Sul  1256291       248574        1007718
8          Centro-Oeste   749148       156048         593101
9              Rondônia    63584        13963          49622
10                 Acre    33379         9121          24258
11             Amazonas   121988        30738          91249
12              Roraima    23977         5880          18098
13                 Pará   248397        58128         190270
14                Amapá    36754         9794          26960
15            Tocantins    71705        13548          58158
16             Maranhão   206222        40667         165555
17                Piauí   128416        25959         102457
18                Ceará   294578        64582         229996
19  Rio Grande do Norte   135434        28273         107161
20              Paraíba   150862        30025         120837
21           Pernambuco   281695        57333         224362
22              Alagoas   106971        20060          86911
23              Sergipe    83176        16801          66376
24                Bahia   434735        80208         354528
25         Minas Gerais   832482       157960         674521
26       Espírito Santo   161332        29788         131544
27       Rio de Janeiro   612263       145864         466399
28            São Paulo  2046321       434677        1611645
29               Paraná   501471        98191         403280
30       Santa Catarina   333537        67571         265964
31    Rio Grande do Sul   421284        82812         338472
32   Mato Grosso do Sul   128352        26911         101443
33          Mato Grosso   141121        27052         114069
34                Goiás   288616        56564         232052
35     Distrito Federal   191061        45521         145538

In [75]:
formacao_saude.to_csv(r"H:\python\3° etapa\atv 3\formacao_saude.csv", sep = ";", encoding="latin1")

In [26]:
import matplotlib.pyplot as plt
import seaborn as sns

In [65]:
formacao_total = formacao_total.rename(columns={0: "uf"})
formacao_total = formacao_total.rename(columns={1: "total"})
formacao_total = formacao_total.rename(columns={2: "total_h"})
formacao_total = formacao_total.rename(columns={3: "total_mulheres"})

In [66]:
formacao_total

                     uf     total total_homens total_mulheres
3                Brasil  25854291     10478534       15375757
4                 Norte   1525166       590558         934609
5              Nordeste   4748933      1744994        3003939
6               Sudeste  12828829      5391638        7437191
7                   Sul   4338861      1768855        2570005
8          Centro-Oeste   2412502       982489        1430013
9              Rondônia    164632        62766         101866
10                 Acre     84300        33291          51009
11             Amazonas    342566       141059         201507
12              Roraima     67045        25585          41460
13                 Pará    601096       229285         371811
14                Amapá     89191        35085          54106
15            Tocantins    176336        63485         112851
16             Maranhão    468681       161352         307329
17                Piauí    304955       108371         196584
18                Ceará    759303       285013         474290
19  Rio Grande do Norte    339913       131178         208735
20              Paraíba    390742       147221         243521
21           Pernambuco    852481       321587         530893
22              Alagoas    267996        98462         169534
23              Sergipe    218255        80608         137646
24                Bahia   1146608       411202         735406
25         Minas Gerais   2615434      1031532        1583902
26       Espírito Santo    491101       193756         297344
27       Rio de Janeiro   2243707       942645        1301062
28            São Paulo   7478587      3223705        4254883
29               Paraná   1687930       695425         992505
30       Santa Catarina   1162515       489557         672958
31    Rio Grande do Sul   1488416       583873         904542
32   Mato Grosso do Sul    366249       145341         220908
33          Mato Grosso    450264       173267         276997
34                Goiás    879270       350828         528443
35     Distrito Federal    716719       313054         403665

In [43]:
# Barras agrupadas: homens x mulheres no Brasil (três recortes)
brasil = pd.DataFrame(
    {
        "area": ["Graduação (total)", "STEM", "Saúde / educação"],
        "homens": [
            formacao_total.loc[formacao_total["uf"] == "Brasil", "total"].item(),
            # formacao_stem.loc[formacao_stem["uf"] == "Brasil", "total_homens"].item()
            # formacao_saude.loc[formacao_saude["uf_regiao"] == "Brasil", "homens"].item(),
        ],
        "mulheres": [
            formacao_total.loc[formacao_total["uf"] == "Brasil", "total"].item(),
            # formacao_stem.loc[formacao_stem["uf"] == "Brasil", "total_mulheres"].item()
            # formacao_saude.loc[formacao_saude["uf_regiao"] == "Brasil", "mulheres"].item(),
        ],
    }
)
brasil_long = brasil.melt(id_vars="area", var_name="sexo", value_name="pessoas")

fig, ax = plt.subplots(figsize=(9, 5))
sns.barplot(data=brasil_long, x="area", y="pessoas", hue="sexo", ax=ax)
ax.set_title("Brasil: pessoas com graduação, por área e sexo")
ax.set_xlabel("Área")
ax.set_ylabel("Pessoas")
plt.tight_layout()
plt.show()

ValueError: All arrays must be of the same length

A tabela deverá ser dividida em 3
- homens e mulheres por região com curso superior
- homens e mulheres por região com curso nas áreas de Ciência, Tecnologia, Engenharias e Matemática
- homens e mulheres por região com curso nas áreas de Educação, Serviços pessoais, Saúde e Bem-estar

Exemplo 1

In [12]:
# : = todas as linhas  |  0:4 = colunas 0, 1, 2 e 3 (as 4 primeiras)
formacao_total = formacao_bruto.iloc[3:36, 0:4].copy()

In [13]:
formacao_total.columns = [
    "uf_regiao",
    "total",
    "total_homens",
    "total_mulheres"
]

In [14]:
formacao_total

              uf_regiao     total total_homens total_mulheres
3                Brasil  25854291     10478534       15375757
4                 Norte   1525166       590558         934609
5              Nordeste   4748933      1744994        3003939
6               Sudeste  12828829      5391638        7437191
7                   Sul   4338861      1768855        2570005
8          Centro-Oeste   2412502       982489        1430013
9              Rondônia    164632        62766         101866
10                 Acre     84300        33291          51009
11             Amazonas    342566       141059         201507
12              Roraima     67045        25585          41460
13                 Pará    601096       229285         371811
14                Amapá     89191        35085          54106
15            Tocantins    176336        63485         112851
16             Maranhão    468681       161352         307329
17                Piauí    304955       108371         196584
18                Ceará    759303       285013         474290
19  Rio Grande do Norte    339913       131178         208735
20              Paraíba    390742       147221         243521
21           Pernambuco    852481       321587         530893
22              Alagoas    267996        98462         169534
23              Sergipe    218255        80608         137646
24                Bahia   1146608       411202         735406
25         Minas Gerais   2615434      1031532        1583902
26       Espírito Santo    491101       193756         297344
27       Rio de Janeiro   2243707       942645        1301062
28            São Paulo   7478587      3223705        4254883
29               Paraná   1687930       695425         992505
30       Santa Catarina   1162515       489557         672958
31    Rio Grande do Sul   1488416       583873         904542
32   Mato Grosso do Sul    366249       145341         220908
33          Mato Grosso    450264       173267         276997
34                Goiás    879270       350828         528443
35     Distrito Federal    716719       313054         403665

In [15]:
formacao_total["percentual_mulheres"] = ((formacao_total['total_mulheres'] / formacao_total['total']) * 100).round(2)